# SPDX-License-Identifer: GPL-3.0-or-later
# This file is part of wslbridge2 project
# Copyright (C) Biswapriyo Nath

# Build image
image:
- Ubuntu2004
- Visual Studio 2022

# Version format
version: "#{build}"

# Do not increment build number after pull requests
pull_requests:
  do_not_increment_build_number: true

# Do not start a new build when a new Git tag is created
skip_tags: true

# Only build for X86_64 architecture
platform: x64

environment:
  backendJob: 'image: Ubuntu2004'

before_build:
- sh: |
    docker build . -t wslbridge2
    docker run --rm wslbridge2 tar -cf - -C /build/bin wslbridge2-backend | tar -xvf -

- cmd: |
    set PATH=C:\cygwin64\bin;%PATH%
    make RELEASE=1

build_script:
- ps: |
    if ($env:APPVEYOR_JOB_NAME -eq $env:backendJob)
    {
        Get-ChildItem .\wslbridge2-backend | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
    }

    if ($env:APPVEYOR_JOB_NAME -ne $env:backendJob)
    {
        $headers = @{ "Content-type" = "application/json" }
        $ProjectUri="https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG"
        $project = Invoke-RestMethod -Uri $ProjectUri -Headers $headers -Method GET
        $jobToWaitJson = $project.build.jobs | where {$_.name -eq $env:backendJob}
        $jobToWaitId = $jobToWaitJson.jobId;

        Start-FileDownload "https://ci.appveyor.com/api/buildjobs/$jobToWaitId/artifacts/wslbridge2-backend"
        Move-Item -path .\wslbridge2-backend .\bin
    }

after_build:
- cmd: |
    del bin\*.obj bin\*.o
    dir /b bin
    7z a -mx9 wslbridge2.zip bin\ > NUL

artifacts:
  - path: wslbridge2.zip
