name: main

on:
  push:
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          show-progress: false
      - name: Build
        run: |
          docker build . -t wslbridge2
          docker run --rm wslbridge2 tar -cf - -C /build/bin wslbridge2-backend | tar -xvf -
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: wslbridge2-backend
          path: wslbridge2-backend

  frontend-msys2:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          show-progress: false
      - name: Install msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true
          install: gcc make
      - name: Build
        shell: msys2 {0}
        run: |
          make RELEASE=1
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: wslbridge2-msys2
          path: bin/wslbridge2.exe

  frontend-cygwin:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          show-progress: false
      - name: Install cygwin
        uses: cygwin/cygwin-install-action@master
        with:
          platform: x86_64
          packages: gcc-g++ make
      - name: Build
        shell: C:\cygwin\bin\bash.exe --noprofile --norc -eo pipefail '{0}'
        run: |
          make RELEASE=1
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: wslbridge2-cygwin
          path: bin/wslbridge2.exe
